### ISSUE TITLE
brand new pattern

### ISSUE THREAD

**Issue by antonmc** [IBM/incubator#40]
Please include details:

- [ ] Why is the pattern is a good idea?

- [ ] What is it's advocacy potential?

- [ ] Is the pattern free to run?

- [ ] What is it's priority?

- [ ] Who will be writing the code?

- [ ] Are we inheriting code?

- [ ] Is it for a product or release launch?

- [ ] Does this pattern fill a gap in our portfolio?

- [ ] Does it overlap with our existing portfolio?

- [ ] Can we partner up with a client?

- [ ] Does this pattern highlight an IBM product advantage vs market product

**Comment by loafyloaf** [comment]
will need:

- [ ] blog
- [ ] video
- [ ] README
