### ISSUE TITLE
best code pattern ever

### ISSUE THREAD

**Issue by loafyloaf** [IBM/incubator#61]
**About this pattern**

_Answer these questions as a comment, then check the boxes prior to proposal review._

- [x] a1. Brief description of your pattern

- [x] a2. Url to your existing repo ( or a not that this is just an idea for now )

- [x] a3. Target completion date ( for instance for an event, or product )?

- [x] a4. Add labels for technology ( e.g. Node, Kubernetes, Swift, Watson etc )

- [x] a5. Are you looking for a collaborator to help publish this (y/n)?

**Pattern content**

_Commit this content prior to publication review._

- [x] c1. Architecture Diagram

- [x] c2. Description - add in readme with the architecture diagram

- [x] c3. Add in additional markdown files such as CONTRIBUTING.MD and MAINTAINERS.MD

- [x] c4. Wiki / Journey Page

- [x] c5. Blog

**Comment by antonmc** [comment]
Having a1, a2, a3 etc is distracting to me as a developer, as a human. Don't make me think ... https://www.amazon.ca/Dont-Make-Think-Revisited-Usability/dp/0321965515/ref=pd_lpo_sbs_14_img_0/131-7814097-4642367?_encoding=UTF8&psc=1&refRID=8ZFWR8SW4N21BWE0N96X
